snapshots:
  - name: products_price_snapshot
    target_schema: "{{ target.schema }}"
    target_database: "{{ target.database }}"
    strategy: timestamp
    unique_key: product_id
    updated_at: price
    invalidate_hard_deletes: true
